name: Build font
on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Download FontForge
        run: |
          wget -O ff.AppImage https://github.com/fontforge/fontforge/releases/download/20230101/FontForge-2023-01-01-a1dad3e-x86_64.AppImage
          chmod +x ff.AppImage
          ./ff.AppImage --appimage-extract > /dev/null
          mv ./squashfs-root ./ff
          rm ff.AppImage

      - name: Run script
        run: './ff/AppRun -script $(pwd)/fontforge.py $(pwd)'

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fonts
          path: |
            output/